# Usage:
#   docker-compose up --force-recreate
version: '2.1'

services:
  #--------------#
  zalenium:
    image: dosel/zalenium
    container_name: zalenium
    hostname: zalenium
    tty: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 4444:4444
    command: >
      start --desiredContainers 30
            --maxDockerSeleniumContainers 30
            --maxTestSessions 25
            --screenWidth 1920 --screenHeight 1080
            --timeZone "Europe/Istanbul"
            --videoRecordingEnabled true
            --keepOnlyFailedTests false
            --debugEnabled true
            --seleniumImageName elgalu/selenium
    environment:
      - HOST_UID
      - HOST_GID