# Note: It requires docker-compose 1.13.0
#
# Usage: docker-compose up -d
version: "2.2"

services:
  #--------------#
  zalenium:
    image: dosel/zalenium
    container_name: zalenium
    hostname: zalenium
    tty: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 4444:4444
    command: >
      start --desiredContainers 30
            --maxDockerSeleniumContainers 30
            --maxTestSessions 25
            --screenWidth 1920 --screenHeight 1080
            --timeZone "Europe/Istanbul"
            --videoRecordingEnabled true
            --keepOnlyFailedTests false
            --debugEnabled true
            --seleniumImageName elgalu/selenium
    environment:
      - HOST_UID
      - HOST_GID

  real_device:
    image: appium/appium
    depends_on:
      - zalenium
    network_mode: "service:zalenium"
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ~/.android:/root/.android
      - $PWD/example/sample_apk:/root/tmp
    environment:
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=zalenium
      # Enable it for msite testing
      #- BROWSER_NAME=chrome

    # Docker-Android for mobile website testing with chrome browser
    # Chrome browser exists only for version 7.0 and 7.1.1
    samsung_galaxy_web_7.1.1:
      image: butomo1989/docker-android-x86-8.1
      privileged: true
      # Increase scale number if needed
      scale: 1
      depends_on:
        - zalenium
        - real_device
      ports:
        - 6080
      volumes:
        - ./video-samsung_7.1.1:/tmp/video
      environment:
        - DEVICE=Samsung Galaxy S6
        - CONNECT_TO_GRID=true
        - APPIUM=true
        - SELENIUM_HOST=zalenium
        - MOBILE_WEB_TEST=true
        - AUTO_RECORD=true

    # Docker-Android for mobile website testing with default browser
    # Default browser exists only for version 5.0.1, 5.1.1 and 6.0
    samsung_galaxy_web_5.1.1:
      image: butomo1989/docker-android-x86-5.1.1
      privileged: true
      # Increase scale number if needed
      scale: 1
      depends_on:
        - zalenium
        - real_device
      ports:
        - 6080
      volumes:
        - ./video-samsung_5.1.1:/tmp/video
      environment:
        - DEVICE=Samsung Galaxy S6
        - CONNECT_TO_GRID=true
        - APPIUM=true
        - SELENIUM_HOST=zalenium
        - MOBILE_WEB_TEST=true
        - AUTO_RECORD=true